name: Codacy Security Scan

on:
  push:
    branches: [ "master"]
  pull_request:
    branches: [ "master"]
  workflow_dispatch:

jobs:
  codacy-security-scan:
    name: Codacy Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
        with:
          output: results.sarif
          format: sarif
          gh-code-scanning-compat: true
          max-allowed-issues: 2147483647
      
      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@main
        with:
          sarif_file: results.sarif
      - name: Adding Summary
        run: | 
            echo "### ANALYSIS SUCCESSFUL" >> $GITHUB_STEP_SUMMARY
            echo "You can find the results [here](https://github.com/Mathmagicians/codacy/security/code-scanning)" >> $GITHUB_STEP_SUMMARY
            echo "or at the [codacy](https://app.codacy.com/gh/Mathmagicians/codacy/dashboard) site" >> $GITHUB_STEP_SUMMARY
          