name: Codacy Analysis CLI

on:
  push:
    branches: [ master ]

jobs:
  codacy-analysis:
    name: Codacy Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.2
      - name: Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@v4.3.0